name: organaki_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  dio: ^5.1.1
  flutter_map: ^3.1.0
  flutter_bloc: ^8.1.2
  bloc: 
  result_dart: ^1.0.6
  latlong2: ^0.8.1
  latlng: ^1.0.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  another_flushbar: ^1.12.30
  go_router: ^7.1.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
     - images/
  #   Put the images inside folder images


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
  fonts:
    - family: Abhaya Libre
      fonts:
        - asset: lib/core/fonts/AbhayaLibre-Regular.ttf
          weight: 400
        - asset: lib/core/fonts/AbhayaLibre-Medium.ttf
          weight: 500
        - asset: lib/core/fonts/AbhayaLibre-SemiBold.ttf
          weight: 600
        - asset: lib/core/fonts/AbhayaLibre-Bold.ttf
          weight: 700
        - asset: lib/core/fonts/AbhayaLibre-ExtraBold.ttf
          weight: 800

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
